### ISSUE TITLE
MojangAPI like patterns and response format

### ISSUE THREAD

**Issue by sgdc3** [games647/MC-REST-API#1]
http://wiki.vg/Mojang_API
and
http://wiki.vg/Authentication

**Comment by TuxCoding** [comment]
Also the same routes? Wouldn't it be enough if just the java proxy converts the data to a Mojang format.

**Comment by sgdc3** [comment]
I'm not sure the proxy would work with any connection, in this case it would be necessary to use the /etc/hosts file to redirect the mojang domains

**Comment by TuxCoding** [comment]
Ah didn't thought about

**Comment by sgdc3** [comment]
Just add it as legacy api, maybe on a subdomain

**Comment by TuxCoding** [comment]
Is authentication really necessary?

**Comment by sgdc3** [comment]
just this:

```
Server
After decrypting the shared secret in the second Encryption Response, the server generates the login hash as above and sends it to

https://sessionserver.mojang.com/session/minecraft/hasJoined?username=username&serverId=hash
(Case sensitive username, must match the client's username!)

The response is a JSON object containing the user's UUID and skin blob

{
    "id": "<profile identifier>",
    "name": "<player name>",
    "properties": [ 
        {
            "name": "textures",
            "value": "<base64 string>",
            "signature": "<base64 string; signed data using Yggdrasil's private key>"
        }
    ]
}
```

**Comment by sgdc3** [comment]
It's the main thing we should cache, as it's the main request made by the vanilla code.

**Comment by sgdc3** [comment]
Wait, is it possible to cache this?

**Comment by sgdc3** [comment]
:/ nope the first login needs to get verified by mojang

**Comment by TuxCoding** [comment]
Indeed. This is used to verify that it's the actual owner of the account.

**Comment by TuxCoding** [comment]
Maybe we could just forward the connection in this case

**Comment by TuxCoding** [comment]
> Wait, is it possible to cache this?

and it's encrypted so we cannot read any data from it.
